# 개발자 여러분 application-test.yml을 application.yml로 사용하세요
spring:
  datasource:
    url: jdbc:mysql://192.168.0.110:3306/lsh_test
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver